# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3Kd9lDkUsD-B9xNxcKNQYjgMEZtE_E9
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4,5,])
y=np.array([0,8,12,20,26,38,])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,0,0,0,0,0,0,0,])
y1=np.array([1, 9, 2, 9, 3, 8, 4, 7,])
x2=np.array([4, 6, 4, 5,4, 4,])
y2=np.array([3, 2,2, 1, 1, 0,])
plt.scatter(x1,y1)
plt.scatter(x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(["60-24","61-24","631-24","630-24"])
y=np.array([16,19,11,22])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(["60-24","61-24","631-24","630-24"])
y=np.array([16,19,11,22])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([63,65,78,])
mylabels=["oliymatemetika","dasturlash","chizmachlik"]
plt.pie(x,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([63,65,78,])
mylabels=["oliymatemetika","dasturlash","chizmachlik"]
myexplode=[0.2,0,0]
plt.pie(x,lables=mylabels,explode=myexplode)
plt.show()